# Use root/example as user/password credentials
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: strongpassowrd
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: strongpassowrd
      ME_CONFIG_MONGODB_URL: mongodb://root:strongpassowrd@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:strongpassowrd@mongo:27017/
    command: sh -c "npm run start"